export const questions = [
  {
    id: "1",
    status: true,
    question: "Search data with debounce",
    view: "/search-with-debounce",
    source:
      "https://github.com/sandip-dev07/react-frontend",
  },
  {
    id: "2",
    status: false,
    question: "Pagination",
    view: "/pagination",
    source: "",
  },
  {
    id: "3",
    status: false,
    question: "OTP input",
    view: "/otp-input",
    source: "",
  },
  {
    id: "4",
    status: false,
    question: "Star rating",
    view: "/star-rating",
    source: "",
  },
  {
    id: "5",
    status: false,
    question: "Progress bar",
    view: "/progress-bar",
    source: "",
  },
  {
    id: "6",
    status: false,
    question: "Nested checkbox",
    view: "/nested-checkbox",
    source: "",
  },
  {
    id: "7",
    status: false,
    question: "Tabs and accordions",
    view: "/tabs-accordions",
    source: "",
  },
  {
    id: "8",
    status: false,
    question: "Tabs form component (Zepto style)",
    view: "/tabs-form",
    source: "",
  },
  {
    id: "9",
    status: false,
    question: "File explorer",
    view: "/file-explorer",
    source: "",
  },
  {
    id: "10",
    status: false,
    question: "Toast notifications",
    view: "/toast-notifications",
    source: "",
  },
  {
    id: "11",
    status: false,
    question: "Drag and drop",
    view: "/drag-drop",
    source: "",
  },
  {
    id: "12",
    status: false,
    question: "Infinite scroll",
    view: "/infinite-scroll",
    source: "",
  },
  {
    id: "13",
    status: false,
    question: "Timer / stopwatch",
    view: "/timer-stopwatch",
    source: "",
  },
  {
    id: "14",
    status: false,
    question: "Shopping cart",
    view: "/shopping-cart",
    source: "",
  },
  {
    id: "15",
    status: false,
    question: "Autocomplete with chip input",
    view: "/autocomplete-chip",
    source: "",
  },
  {
    id: "16",
    status: false,
    question: "Carousel / slider",
    view: "/carousel-slider",
    source: "",
  },
  {
    id: "17",
    status: false,
    question: "Todo App",
    view: "/todo-app",
    source: "",
  },
  {
    id: "18",
    status: false,
    question: "Data visualization",
    view: "/data-visualization",
    source: "",
  },
  {
    id: "19",
    status: false,
    question: "Nested comments",
    view: "/nested-comments",
    source: "",
  },
  {
    id: "20",
    status: false,
    question: "Modal dialogs",
    view: "/modal-dialogs",
    source: "",
  },
  {
    id: "21",
    status: false,
    question: "Memory game",
    view: "/memory-game",
    source: "",
  },
  {
    id: "22",
    status: false,
    question: "Crypto converter",
    view: "/crypto-converter",
    source: "",
  },
  {
    id: "23",
    status: false,
    question: "Google Calendar clone",
    view: "/google-calendar-clone",
    source: "",
  },
  {
    id: "24",
    status: false,
    question: "Search autocomplete",
    view: "/search-autocomplete",
    source: "",
  },
  {
    id: "25",
    status: false,
    question: "Breadcrumb navigation",
    view: "/breadcrumb-navigation",
    source: "",
  },
];
